"""empty message

Revision ID: ca24a81012bd
Revises: e267b9160411
Create Date: 2019-02-17 00:50:44.311160

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ca24a81012bd'
down_revision = 'e267b9160411'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('endorsement')
    op.alter_column('studysession', 'start_time', existing_type=sa.DateTime(), type_=sa.String(30))
    op.alter_column('studysession', 'end_time', existing_type=sa.DateTime(), type_=sa.String(30))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('studysession', 'start_time', existing_type=sa.String(30), type_=sa.DateTime())
    op.alter_column('studysession', 'end_time', existing_type=sa.String(30), type_=sa.DateTime())
    op.create_table('endorsement',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('receiver_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('endorser_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['endorser_id'], ['user.id'], name='endorsement_ibfk_2'),
    sa.ForeignKeyConstraint(['receiver_id'], ['user.id'], name='endorsement_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
