"""empty message

Revision ID: e267b9160411
Revises: 
Create Date: 2019-02-17 00:04:53.691358

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e267b9160411'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('studysession', sa.Column('building', sa.String(length=50), nullable=False))
    op.add_column('studysession', sa.Column('location', sa.String(length=100), nullable=True))
    op.add_column('studysession', sa.Column('notes', sa.String(length=200), nullable=True))
    op.add_column('user', sa.Column('name', sa.String(length=50), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'name')
    op.drop_column('studysession', 'notes')
    op.drop_column('studysession', 'location')
    op.drop_column('studysession', 'building')
    # ### end Alembic commands ###
